config/routes.rb
Rails.application.routes.draw do

  # devise_for :users, path: '/suckers'
  devise_for :users, skip: :all
  devise_scope :user do
    get '/users/sign_up'  => 'front/users/registrations#new',  as: :new_user_registration
    post '/users/sign_up'  => 'front/users/registrations#create', as: :user_registration
    get '/users/edit' => 'front/users/registrations#edit', as: :edit_user_registration
    delete '/users/sign_out' => 'front/users/registrations#destroy', as: :destroy_user_session

    get '/users/sign_in' => 'front/users/sessions#new', as: :new_user_session
    post '/users/sign_in'  => 'front/users/sessions#create', as: :user_session
  end
  
  scope module: :front do

    

    root 'static_pages#home'
    resources :requests
    resources :events, only: :show
  end

  namespace :admin do
    get '', to: 'dashboard#home', as: '/'
    resources :requests
    resources :events, except: :show
    resources :speakers, except: :show
    resources :organizers, except: :show
    resources :users
    resources :ticket_types, except: :show
    resources :archives, except: :show
    resources :settings, except: :show
    get '/requests/:id/decline', to: 'requests#decline', as: :decline_request
    get '/requests/:id/approve', to: 'requests#approve', as: :approve_request
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/navigation/_alerts.html.haml
-flash.each do |name, msg|
  =content_tag(:div, msg, class: "panel panel-#{name}") do
    .panel-heading
      %i.fa.fa-warning
      =name
    .panel-body
      =msg

app/views/admin/navigation/_breadcrumbs.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    / Calling a helper (admin_helper.rb) method (which relies on session[:breadcrumbs])
    =breadcrumbs
  .col-lg-2

app/views/admin/navigation/_footer.html.haml
.footer
  .pull-right
    10GB of
    %strong 250GB
    Free.
  %div
    %strong Copyright
    Yadadya.Creations © 2014-2017

app/views/admin/navigation/_header.html.haml
.row.border-bottom
  %nav.navbar.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
    .navbar-header
      %a.navbar-minimalize.minimalize-styl-2.btn.btn-primary{:href => "#"}
        %i.fa.fa-bars
      %form.navbar-form-custom{:action => "#", :method => "post", :role => "search"}
        .form-group
          %input#top-search.form-control{:name => "top-search", :placeholder => "Search for something...", :type => "text"}/
    %ul.nav.navbar-top-links.navbar-right
      %li
        =link_to destroy_user_session_path, method: :delete do
          %i.fa.fa-sign-out
          =t('admin.logout')
      %li
        %a.right-sidebar-toggle
          %i.fa.fa-tasks

app/views/admin/navigation/_left_menu.html.haml
%nav.navbar-default.navbar-static-side{:role => "navigation"}
  .sidebar-collapse
    %ul#side-menu.nav.metismenu
      %li.nav-header
        .dropdown.profile-element
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %span.clear
              %span.block.m-t-xs
                %strong.font-bold
                  -if current_user
                    =current_user.email
              %span.text-muted.text-xs.block
                Art Director
                %b.caret
          %ul.dropdown-menu.animated.fadeInRight.m-t-xs
            -if current_user
              %li
                =link_to edit_user_registration_path(current_user.id) do
                  =t('admin.profile')
              %li
                =link_to destroy_user_session_path do
                  =t('admin.logout')
        .logo-element
          IN+
      =nav_link admin_path do
        %i.fa.fa-area-chart
        %span.nav-label
          =t('admin.navigation.dashboard')
      =nav_link "" do
        %i.fa.fa-newspaper-o
        %span.nav-label
          Заявки
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Только текущие заявки", admin_requests_path(only_current: true)
          %li
            =link_to "Все заявки", admin_requests_path
          %li
            =link_to "Новая заявка", new_admin_request_path

      =nav_link "" do
        %i.fa.fa-calendar-o
        %span.nav-label
          Мероприятия
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Все мероприятия", admin_events_path
          %li
            =link_to "Новое мероприятие", new_admin_event_path

      =nav_link "" do
        %i.fa.fa-user-circle-o
        %span.nav-label
          Спикеры
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Все спикеры", admin_speakers_path
          %li
            =link_to "Новый спикер", new_admin_speaker_path

      =nav_link "" do
        %i.fa.fa-linode
        %span.nav-label
          Организаторы
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Все организаторы", admin_organizers_path
          %li
            =link_to "Новый организатор", new_admin_organizer_path

      =nav_link "" do
        %i.fa.fa-hand-peace-o
        %span.nav-label
          Люди
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Только текущее мероприятие", admin_users_path(current: true)
          %li
            =link_to "Все зарегистрировавшиеся", admin_users_path

      =nav_link "" do
        %i.fa.fa-ticket
        %span.nav-label
          Типы билетов
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Все типы билетов", admin_ticket_types_path
          %li
            =link_to "Новый тип", new_admin_ticket_type_path


      =nav_link "" do
        %i.fa.fa-file-archive-o
        %span.nav-label
          Архив
        %span.fa.arrow
        %ul.nav.nav-second-level.collapse
          %li.active
            =link_to "Все записи", admin_archives_path
          %li
            =link_to "Новая запись", new_admin_archive_path


      =nav_link admin_settings_path do
        %i.fa.fa-cog
        %span.nav-label
          Настройки

app/views/admin/navigation/_right_sidebar.html.haml
#right-sidebar.animated
  .sidebar-container
    %ul.nav.nav-tabs.navs-3
      %li.active
        %a{"data-toggle" => "tab", :href => "#tab-1"}
          %i.fa.fa-gear
    .tab-content
      #tab-1.tab-pane.active
        .sidebar-title
        
        .sidebar-content
          %h4 Settings
          .small
            I belive that. Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            And typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
            Over the years, sometimes by accident, sometimes on purpose (injected humour and the like).